[package]
name = "mcfetch"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
regex = "1.10.6"
sysinfo = "0.31.4"
uname = "0.1.1"
users = "0.11.0"
